baseurl: /jekyll-maps
url: https://ovrdc.github.io
title: Material Maps


#Jekyll ignores folders with underscores unless otherwise noted
collections:
  maps:
    output: true

defaults:
  - scope:
      path: ""
      type: maps
    values:
      layout: map
