baseurl: /material-maps
url: https://ovrdc.github.io
title: Material Maps

exclude: ["Gemfile", "Gemfile.lock"]

#compress settings remove blank lines
compress_html:
  blanklines: true

#Jekyll ignores folders with underscores unless otherwise noted
collections:
  maps:
    output: true

defaults:
  - scope:
      type: "posts"
    values:
      layout: default
      permalink: /maps/:title/
      map: true
      subtitle: this is a subtitle
      basemap: contrast
      tags: services
      image: counties.jpg
      center: "[39, -83.4]"
      zoom: 14
      api: leaflet

# Prose.io Config File
prose:
  siteurl: "https://ovrdc.github.io/material-maps/"
  media: "/assets/post-images/"
  metadata:
    "":
      - name: "basemap"
        field:
          element: select
          label: Basemap
          options:
            - name: "Dark"
              value: contrast
            - name: "Streets"
              value: streets
