baseurl: /material-maps
url: https://ovrdc.github.io
title: Material Maps

exclude: ["Gemfile", "Gemfile.lock"]

#Jekyll ignores folders with underscores unless otherwise noted
collections:
  maps:
    output: true

defaults:
  - scope:
      path: ""
      type: maps
    values:
      layout: map
      
# Prose.io Config File
prose:
  siteurl: "https://ovrdc.github.io/material-maps/"
  media: "/_maps/images/"
  metadata: 
    "":
      - name: "basemap"
        field: 
          element: select
          label: Basemap
          options:
            - name: "Dark"
              value: dark
            - name: "Streets"
              value: streets
