baseurl: /material-maps
url: https://ovrdc.github.io
title: Material Maps


#Jekyll ignores folders with underscores unless otherwise noted
collections:
  maps:
    output: true

defaults:
  - scope:
      path: ""
      type: maps
    values:
      layout: map
      
# Prose.io Config File
siteurl: "https://ovrdc.github.io/material-maps/"
media: "/_maps/images/"
metadata: 
  _pages:
    - name: "basemap"
      field: 
        element: select
        label: Basemap
        options:
          - name: "Dark"
            value: dark
          - name: "Streets"
            value: streets
